name: PR checkstyle
on:
  workflow_dispatch:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run codestyle check
        env:
          GENERATE_SOURCEMAP: false
          CI: false
          JAVA_OPTS: "-Xms512m -Xmx512m"
        run: ./gradlew clean checkstyleMain checkstyleTest ${{ github.event.inputs.buildOptions }}
